const Roles = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  DATA_COLLECTOR: "DATA_COLLECTOR",
  DATA_INTERPRETER: "DATA_INTERPRETER",
  BANKER: "BANKER",
  VALUER: "VALUER",
  INDIVIDUAL: "INDIVIDUAL",
  BROKER: "BROKER",
};

module.exports = Roles;
