const mongoose = require("mongoose");
const { Schema } = mongoose;
mongoose.pluralize(null);

const roles = [
  "SUPER_ADMIN",
  "PROPERTY_MANAGER",
  "ADMIN",
  "DATA_COLLECTOR",
  "DATA_INTERPRETER",
  "BANKER",
  "VALUER",
  "INDIVIDUAL",
  "BROKER",
];
const bankerRoles = [
  "",
  "Adani Capital Pvt. Ltd.",
  "Adani Housing Finance Pvt. Ltd.",
  "ART Housing Finance",
  "Axis Bank",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Baroda Gujarat Gramin Bank",
  "Canara Bank",
  "Central Bank of India",
  "City Union Bank",
  "Corporation Bank",
  "DRT Ahmedabad",
  "Easy Housing Finance Ltd.",
  "Electronica Finance Ltd.",
  "Federal Bank",
  "Fullerton India Credit Company Ltd.",
  "Fusion Micro Finance Ltd.",
  "HDFC Bank",
  "Hero Housing Finance",
  "Hindustan Fluorocarbon Ltd.",
  "Home First Finance Company",
  "Home First Finance Company India Ltd. (HFFC)",
  "ICICI Bank",
  "IDBI Bank",
  "Indian Bank",
  "Indian Overseas Bank",
  "IndusInd Bank",
  "Jana Housing Finance Limited",
  "Jana Small Finance Bank",
  "Kotak Mahindra Prime Ltd.",
  "MAS Financial Services",
  "Neo Leaf Housing Finance",
  "PNB Housing Finance",
  "PNB Housing Finance Ltd.",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "Shamrao Vitthal Co-operative Bank",
  "State Bank of India",
  "Sutex Bank",
  "SVC Co-operative Bank Ltd.",
  "SRG Housing Finance",
  "UCO Bank",
  "Ujjivan Small Finance Bank",
  "Union Bank of India",
  "Yes Bank Ltd.",
];

const UserSchema = new Schema(
  {
    role: { type: String, enum: roles, default: "BANKER" },
    name: { type: String, trim: true },
    phone: { type: String },
    banker_role_value: { type: String, enum: bankerRoles },
    // subscriptions: [{ type: Schema.Types.ObjectId, ref: 'subscription' }],
    subscriptions_id: { type: Schema.Types.ObjectId, ref: "subscription" },
    email: {
      type: String,
      unique: true,
      match: [
        /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
        "Enter a valid email address",
      ],
      lowercase: true,
      trim: true,
    },
    password: { type: String, trim: true },
    module: { type: Array },
    otp: { type: Number },
    forgot_otp: { type: Number },
    is_paid: { type: Boolean, default: true },
    no_of_report: { type: Number, default: 0 },
    login_attempts: { type: Number, default: 0 },
    no_of_pdf: { type: Number, default: 0 },
    is_verified: { type: Boolean, default: false },
    is_new: { type: Boolean, default: true },
    status: { type: String, trim: true },
    is_active: { type: Boolean, default: false },
    last_login: { type: Date },
    subscriptions_expire: { type: Date },
  },
  { versionKey: false, timestamps: true }
);

module.exports = mongoose.model("user", UserSchema);
